--- #YAML:1.0
name:               Linux-DVB-DVBT-Apps-QuartzPVR
version:            0.02
abstract:           PVR Application 
author:
    - Steve Price <cpan@quartz-net.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    App::Framework:       Config::Crontab
    Data::Dumper:         Linux::DVB::DVBT
    Date::Manip:          MP3::Tag
    DBI:                  DBD::mysql
    File::Basename:       0
    File::Path:           0
    File::Spec:           0
    Linux::DVB::DVBT::TS:  Linux::DVB::DVBT::Advert
    Pod::Coverage:        0.18
    POSIX:                0
    Test::Pod:            1.22
    Test::Pod::Coverage:  1.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
